/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AIChat {
  export type MessageStruct = {
    prompt: string;
    reply: string;
    plugin: string;
    status: string;
  };

  export type MessageStructOutput = [
    prompt: string,
    reply: string,
    plugin: string,
    status: string
  ] & { prompt: string; reply: string; plugin: string; status: string };
}

export interface AIChatInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "history"
      | "message"
      | "messageCount"
      | "messages"
      | "processPrompt"
      | "roflAppID"
      | "submitAgentReply"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentReplied" | "MessageSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "history",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "message",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "messageCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "messages", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPrompt",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "roflAppID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitAgentReply",
    values: [AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "history", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "message", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPrompt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roflAppID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAgentReply",
    data: BytesLike
  ): Result;
}

export namespace AgentRepliedEvent {
  export type InputTuple = [
    user: AddressLike,
    messageId: BigNumberish,
    reply: string
  ];
  export type OutputTuple = [user: string, messageId: bigint, reply: string];
  export interface OutputObject {
    user: string;
    messageId: bigint;
    reply: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [user: AddressLike, messageId: BigNumberish];
  export type OutputTuple = [user: string, messageId: bigint];
  export interface OutputObject {
    user: string;
    messageId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AIChat extends BaseContract {
  connect(runner?: ContractRunner | null): AIChat;
  waitForDeployment(): Promise<this>;

  interface: AIChatInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  history: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string] & {
        prompt: string;
        reply: string;
        plugin: string;
        status: string;
      }
    ],
    "view"
  >;

  message: TypedContractMethod<
    [userId: AddressLike, messageId: BigNumberish],
    [AIChat.MessageStructOutput],
    "view"
  >;

  messageCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  messages: TypedContractMethod<[], [bigint], "view">;

  processPrompt: TypedContractMethod<
    [prompt: string, plugin: string],
    [void],
    "nonpayable"
  >;

  roflAppID: TypedContractMethod<[], [string], "view">;

  submitAgentReply: TypedContractMethod<
    [userId: AddressLike, messageId: BigNumberish, reply: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "history"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, string] & {
        prompt: string;
        reply: string;
        plugin: string;
        status: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "message"
  ): TypedContractMethod<
    [userId: AddressLike, messageId: BigNumberish],
    [AIChat.MessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "messageCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "processPrompt"
  ): TypedContractMethod<
    [prompt: string, plugin: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roflAppID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitAgentReply"
  ): TypedContractMethod<
    [userId: AddressLike, messageId: BigNumberish, reply: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentReplied"
  ): TypedContractEvent<
    AgentRepliedEvent.InputTuple,
    AgentRepliedEvent.OutputTuple,
    AgentRepliedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;

  filters: {
    "AgentReplied(address,uint256,string)": TypedContractEvent<
      AgentRepliedEvent.InputTuple,
      AgentRepliedEvent.OutputTuple,
      AgentRepliedEvent.OutputObject
    >;
    AgentReplied: TypedContractEvent<
      AgentRepliedEvent.InputTuple,
      AgentRepliedEvent.OutputTuple,
      AgentRepliedEvent.OutputObject
    >;

    "MessageSent(address,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
  };
}
