/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oasisprotocol from "./@oasisprotocol";
export type { oasisprotocol };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Subcall } from "./@oasisprotocol/sapphire-contracts/contracts/Subcall";
export { Subcall__factory } from "./factories/@oasisprotocol/sapphire-contracts/contracts/Subcall__factory";
export type { AIChat } from "./contracts/Chat.sol/AIChat";
export { AIChat__factory } from "./factories/contracts/Chat.sol/AIChat__factory";
